apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service2-vsvc
spec:
  hosts:
  - service2.istio-test.svc.cluster.local
  http:
  - route:
    name: primary
    - destination:
        host: stable-svc
      weight: 100
    - destination:
        host: canary-svc
      weight: 0