apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: service2-vsvc
spec:
  hosts:
  - service2.istio-test.svc.cluster.local
  http:
  - name: primary
    route:
      - destination:
          host: service2
        weight: 100
      - destination:
          host: service2-canary
        weight: 0